---
title: "final project"
author: "Yifei Sun"
date: "2022-12-01"
output: html_document
---


# INCLUDE IN MODEL:
- weather 
- holiday
- weekend
- nearest neighbor?
- from station
- to station

DEPENDENT VARIABLE: delay time minutes




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup_13, cache=TRUE, message=FALSE}
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(tidycensus)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.2),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette5 <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4 <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette2 <- c("#6baed6","#08519c")
```



```{r read_dat }
dat <- read.csv("TrainData_Cleaned.csv")
station <-read.csv("stops.csv")


dat <- TrainData_Cleaned
station <- stops

dat<-merge(dat, station, by.x="from", by.y="stop_name")
dat <- dat%>%
  rename(
         from_lat = stop_lat,
         from_lng = stop_lon)
dat<-merge(dat, station, by.x="to", by.y="stop_name")
dat <- dat%>%
  rename(
         to_lat = stop_lat,
         to_lng = stop_lon,%>%
  dplyr::select(-stop_id.x,-stop_code.x,-stop_id.y,-stop_code.y)
  na.omit(dat)
  
  
  
  
dat$scheduled_time <- mdy_hm(dat$scheduled_time)  
dat$actual_time <- mdy_hm(dat$actual_time)

dat$holiday <- ifelse(yday(dat$scheduled_time)%in% c(
  #New Years
  "365", "1", "2", 
  # St. Patrick's Day
  "76",
  #Christmas
  "359"
  ), 1,0) 


```

```{r import_weather, message = FALSE, warning = FALSE }
#riem_networks()
#riem_stations("NY_ASOS")

weather.Data <- 
  riem_measures(station = "NYC", date_start = "2018-01-01", date_end = "2018-01-31")
weather.Panel  <-  
  weather.Data %>%
  dplyr::select(valid, tmpf, p01i, sknt, vsby)%>%
  replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Precipitation = sum(p01i),
              Wind_Speed = max(sknt),
              Visibility = max(vsby)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))



```

riem_networks()


```{r plot_weather, catche = TRUE}
grid.arrange( ncol=4,
  ggplot(weather.Panel, aes(interval60,Precipitation)) + geom_line() + 
  labs(title="Percipitation", x="Hour", y="Perecipitation") + plotTheme,
  ggplot(weather.Panel, aes(interval60,Wind_Speed)) + geom_line() + 
    labs(title="Wind Speed", x="Hour", y="Wind Speed") + plotTheme,
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line() + 
    labs(title="Temperature", x="Hour", y="Temperature") + plotTheme,
  ggplot(weather.Panel, aes(interval60,Visibility)) + geom_line() + 
    labs(title="Temperature", x="Hour", y="Visibility") + plotTheme,
  top="Weather Data - NYC Metro Area - 2018")






grid.arrange( ncol=1,
  ggplot(weather.Panel, aes(interval60,Visibility)) + geom_line() + 
    labs(title="Temperature", x="Hour", y="Visibility") + plotTheme,
  top="Weather Data - NYC Metro Area - 2018")


```





```{r mean_trips_hist, warning = FALSE, message = FALSE }
dat %>%
        mutate(time_of_day = case_when(hour(scheduled_time) < 7 | hour(scheduled_time) > 18 ~ "Overnight",
                                 hour(scheduled_time) >= 7 & hour(scheduled_time) < 10 ~ "AM Rush",
                                 hour(scheduled_time) >= 10 & hour(scheduled_time) < 15 ~ "Mid-Day",
                                 hour(scheduled_time) >= 15 & hour(scheduled_time) <= 18 ~ "PM Rush"))%>%
         group_by(scheduled_time, from, time_of_day) %>%
         tally()%>%
  group_by(from, time_of_day)%>%
  summarize(mean_trips = mean(n))%>%
  ggplot()+
  geom_histogram(aes(mean_trips), binwidth = 1)+
  labs(title="Mean Number of Hourly Trips Per Station. Chicago, May, 2018",
       x="Number of trips", 
       y="Frequency")+
  facet_wrap(~time_of_day)+
  plotTheme
```




glimpse(dat)






